import { Link } from "react-router-dom";

export default function Terms() {
  const year = new Date().getFullYear();

  return (
    <div className="min-h-[100dvh] bg-zinc-950 text-zinc-100">
      <div className="mx-auto max-w-3xl space-y-6 px-6 py-16">
        <h1 className="mb-6 text-2xl font-semibold tracking-tight">
          Terms of Service
        </h1>

        <p className="text-sm leading-relaxed text-zinc-400">
          <span className="font-medium text-zinc-300">Terms of Service</span>
          <br />
          Last updated: {year}
        </p>

        <p className="text-sm leading-relaxed text-zinc-300">
          By using Sclearn you agree to the following terms.
        </p>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-zinc-100">
            Use of the Service
          </h2>
          <p className="text-sm leading-relaxed text-zinc-300">
            Sclearn provides AI-generated flashcards based on user-submitted
            notes. The service is intended for educational and personal use.
          </p>
          <p className="text-sm leading-relaxed text-zinc-300">You agree not to:</p>
          <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed text-zinc-300">
            <li>misuse the platform</li>
            <li>attempt to bypass usage limits</li>
            <li>use the service for illegal or abusive purposes</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-zinc-100">Accounts</h2>
          <p className="text-sm leading-relaxed text-zinc-300">
            You are responsible for maintaining the security of your account.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-zinc-100">
            Service Availability
          </h2>
          <p className="text-sm leading-relaxed text-zinc-300">
            The service may change, be interrupted, or be discontinued at any time
            without notice.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-zinc-100">
            AI Generated Content
          </h2>
          <p className="text-sm leading-relaxed text-zinc-300">
            Flashcards are generated by artificial intelligence and may contain
            errors. Users should verify information before relying on the
            content.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-zinc-100">
            Limitation of Liability
          </h2>
          <p className="text-sm leading-relaxed text-zinc-300">
            Sclearn is provided &quot;as is&quot; without guarantees. The site
            operator is not responsible for damages resulting from use of the
            service.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-zinc-100">Changes to Terms</h2>
          <p className="text-sm leading-relaxed text-zinc-300">
            These terms may be updated periodically.
          </p>
        </section>

        <div className="pt-8">
          <Link
            to="/"
            className="inline-flex min-h-[44px] touch-manipulation items-center text-emerald-400 hover:text-emerald-300"
          >
            ← Back
          </Link>
        </div>
      </div>
    </div>
  );
}
